# action.,yml

# ███╗   ███╗███████╗████████╗████████╗██╗     ███████╗ ██████╗██╗
# ████╗ ████║██╔════╝╚══██╔══╝╚══██╔══╝██║     ██╔════╝██╔════╝██║
# ██╔████╔██║█████╗     ██║      ██║   ██║     █████╗  ██║     ██║
# ██║╚██╔╝██║██╔══╝     ██║      ██║   ██║     ██╔══╝  ██║     ██║
# ██║ ╚═╝ ██║███████╗   ██║      ██║   ███████╗███████╗╚██████╗██║
# ╚═╝     ╚═╝╚══════╝   ╚═╝      ╚═╝   ╚══════╝╚══════╝ ╚═════╝╚═╝
# MettleCI DevOps for DataStage       (C) 2025-2026 Data Migrators
#                     _                          _           _
#   __ _ ___ ___  ___| |_       __ _ _ __   __ _| |_   _ ___(_)___
#  / _` / __/ __|/ _ \ __|____ / _` | '_ \ / _` | | | | / __| / __|
# | (_| \__ \__ \  __/ ||_____| (_| | | | | (_| | | |_| \__ \ \__ \
#  \__,_|___/___/\___|\__|     \__,_|_| |_|\__,_|_|\__, |___/_|___/
#  _            _                                  |___/
# | |_ ___  ___| |_
# | __/ _ \/ __| __|
# | ||  __/\__ \ |_
#  \__\___||___/\__|
# 

name: 'MCIX Asset-Analysis Test'
author: 'Data Migrators Pty Ltd'
description: 'Run asset analysis tests on DataStage assets in an IBM Software Hub (Cloud Pak) project using the MettleCI MCIX CLI'
branding:
  icon: 'search'
  color: 'blue'

# Note that true/false boolean inputs accept:
# 1, true, TRUE, yes, YES, on, ON, and 
# 0, false, FALSE, no, NO, off, OFF
inputs:
  api-key:
    description: 'API key for authentication'
    required: true

  url:
    description: 'URL of the DataStage server'
    required: true

  user:
    description: 'Username for authentication'
    required: true

  report:
    description: 'Path to output the asset analysis report'
    required: false
    default: 'reports/asset-analysis-report.xml'

  project:
    description: 'DataStage project name'
    required: false     # Required when -project-id not specified
    default: ''

  project-id:
    description: 'DataStage project id'
    required: false     # Required when -project not specified
    default: ''

  path:
    description: 'Path to the DataStage assets. Mutually exclusive with url/user/api-key.'
    required: true

  rules:
    description: 'Path to the compliance rules'
    required: true

  include-tags:
    description: 'Comma-separated list of tags to include'
    required: false
    default: ''
  
  exclude-tags:
    description: 'Comma-separated list of tags to exclude'
    required: false
    default: ''

  test-suite:
    description: 'Test suite name'
    required: false
    default: 'mcix tests'

  ignore-test-failures:
    description: 'Ignore test failures (always return 0)? (true/false)'
    required: false
    default: 'false'

  additional-args:
    description: 'Additional raw arguments to append to the mcix command'
    required: false

outputs:
  return-code:
    description: 'The return code of the command'
  junit-path:
    description: 'Path to the JUnit XML report generated by mcix asset-analysis test'

runs:
  using: 'composite'
  steps:
    - name: asset-analysis test is not yet available
      shell: bash
      run: |
        set +x

        echo "The MCIX 'asset-analysis test' command is not yet avaiable for use, but will be enabled in a future release"
        exit 1


  # using: docker
  # image: Dockerfile
  # env:
  #   PARAM_API_KEY: ${{ inputs.api-key }}
  #   PARAM_URL: ${{ inputs.url }}
  #   PARAM_USER: ${{ inputs.user }}
  #   PARAM_REPORT: ${{ inputs.report }}
  #   PARAM_PROJECT: ${{ inputs.project }}
  #   PARAM_PROJECT_ID: ${{ inputs.project-id }}
  #   PARAM_PATH: ${{ inputs.path }}
  #   PARAM_RULES: ${{ inputs.rules }}
  #   PARAM_INCLUDE_TAGS: ${{ inputs.include-tags }}
  #   PARAM_EXCLUDE_TAGS: ${{ inputs.exclude-tags }}
  #   PARAM_TEST_SUITE: ${{ inputs.test-suite }}
  #   PARAM_IGNORE_TEST_FAILURES: ${{ inputs.ignore-test-failures }}
  #   PARAM_ADDITIONAL_ARGS: ${{ inputs.additional-args }}
